// src/components/datenbank.vue
<template>
  <q-card inline style="width: 300px; margin: 5px">
    <q-card-section>
      <div class="text-h6">Datenbank</div>
    </q-card-section>
    <q-separator />
    <q-card-section>
      <q-input
        label="Server"
        placeholder="z.B. localhost oder 192.168.178.99"
        v-model="db.connection.host"
        :autofocus="autofocus"
        @keyup.enter="handleSubmit"
      />
    </q-card-section>
    <q-card-section>
      <q-input
        label="Datenbank"
        placeholder="Name der Datenbank, z.B. schild_berufskolleg"
        v-model="db.connection.database"
        @keyup.enter="handleSubmit"
      />
    </q-card-section>
    <q-card-section>
      <q-input label="Benutzername"
        v-model="db.connection.user"
        @keyup.enter="handleSubmit"
      />
    </q-card-section>
    <q-card-section>
      <q-input
        type="password"
        no-pass-toggle
        label="Passwort"
        v-model="db.connection.password"
        @keyup.enter="handleSubmit"
      />
    </q-card-section>
    <q-expansion-item
        expand-separator
        dense
        icon="warning"
        label="Erweiterte Einstellungen"
    >
      <q-card-section>
        <q-input
          type="text"
          label="Zeitzone"
          hint="['local', 'Z' oder als Offset +HH:MM / -HH:MM]"
          v-model="db.connection.timezone"
        />
      </q-card-section>
      <q-card-section>
        <q-checkbox
          label="Daten als String"
          v-model="db.connection.dateStrings"
        />
      </q-card-section>
      <q-card-section>
        <q-input
          type="text"
          label="Zeichensatz"
          hint="['utf8']"
          v-model="db.connection.charset"
        />
      </q-card-section>
    </q-expansion-item>
    <q-card-section>
      <q-btn color="primary" @click="handleSubmit">{{checkConnection}}</q-btn>
      <q-icon class="q-display-1" v-if="testing" :color="testing" name="lens" />
    </q-card-section>
  </q-card>
</template>

<script>
const { ipcRenderer: ipc } = require('electron-better-ipc')

export default {
  data () {
    return {
      autofocus: this.$route.name === 'datenbank',
      checkConnection: 'Verbindung prüfen …',
      configData: this.$store.state.data.configData,
      testing: null,
      db: this.$store.state.data.configData.db || {
        client: 'mysql',
        useNullAsDefault: true,
        connection: { host: '', database: '', user: '', password: '', charset: 'utf8' }
      }
    }
  },
  methods: {
    async handleSubmit () {
      await ipc.callMain('schildConnect', this.db)
      if (this.testing !== 'green') {
        try {
          const res = await ipc.callMain('schildTestConnection')
          if (!res) throw new Error('Die Verbindung konnte nicht hergestellt werden.')
          else this.testing = 'green'
          this.checkConnection = 'Verbindungsdaten speichern'
          this.configData.db = this.db
          this.$store.commit('data/updateConfigData', this.configData)
          const schule = await ipc.callMain('schildGetSchule')
          this.$store.commit('data/updateSchule', schule)
          this.$router.push('/')
        } catch (error) {
          console.log(error)
          this.testing = 'red'
          this.checkConnection = 'Fehlerhafte Verbindungsdaten'
        }
      } else this.$emit('input', this.db)
    }
  }
}
</script>

// src/components/Datenbank.svelte
<script>
  import { onMount } from 'svelte';
  import { schild } from './App.svelte'
  import { configData, state } from './../stores.js';
  export let connected
  let host_form
  let fehler = false

  const db = $configData.db && $configData.db.connection || {}

	onMount(async () => {
    host_form.focus()
  })

  const key = e => {
    if (e.key === "Enter") {
      connect()
      e.preventDefault();
    } else return
  };
  const connect = async _ => {
    try {
      await schild.connect({client: 'mysql', connection: db})
      $state.connected = await schild.testConnection()
      connected = true
      fehler = false
      $configData.db = {client: 'mysql', useNullAsDefault: true, connection: db}
      if (!$state.connected) throw 'Fehler'
    } catch (e) {
      console.log(e)
      connected = false
      fehler = true
    }
  }
</script>

<div class="box">
  <p class="subtitle is-4 has-text-grey has-text-centered">Datenbank</p><br>
    <div class="field">
      <label class="label">Server</label>
      <p class="control">
        <input class="input"
                type="text"
                placeholder="z.B. localhost oder 192.168.178.99"
                bind:this={host_form}
                on:keydown={key}
                bind:value={db.host}>
      </p>
    </div>
    <div class="field">
      <label class="label">Datenbank</label>
      <p class="control">
        <input class="input"
                type="text"
                placeholder="Datenbank"
                on:keydown={key}
                bind:value={db.database}>
      </p>
    </div>
    <div class="field">
      <label class="label">Benutzer</label>
      <p class="control">
        <input class="input"
                type="text"
                placeholder="Benutzername"
                on:keydown={key}
                bind:value={db.user}>
      </p>
    </div>
    <div class="field">
      <label class="label">Passwort</label>
      <p class="control">
        <input class="input"
                type="password"
                placeholder="Passwort"
                on:keydown={key}
                bind:value={db.password}>
      </p>
    </div>
    <div class="field">
      <label class="label">Daten als String</label>
      <p class="control">
        <label class="checkbox">
          <input type="checkbox" bind:checked={db.dateStrings}>
            Daten als String verwenden – verhindert Probleme bei Geburtsdaten etc.
        </label>
      </p>
    </div>
    <div class="field">
      <label class="label">MySQL Debug-Modus</label>
      <p class="control">
        <label class="checkbox">
          <input type="checkbox" bind:checked={db.debug}>
          Alle MySQL-Anfragen werden in der Konsole ausgegeben.
        </label>
      </p>
    </div>
    <div class="field">
      <label class="label">Zeitzone</label>
      <p class="control">
        <input class="input"
                type="text"
                placeholder="'local', 'Z' oder als Offset +HH:MM / -HH:MM"
                on:keydown={key}
                bind:value={db.timezone}>
      </p>
    </div>
    <div class="field">
      <label class="label">Zeichensatz</label>
      <p class="control">
        <input class="input"
                type="text"
                placeholder="utf8"
                on:keydown={key}
                bind:value={db.charset}>
      </p>
    </div>
    <button class="button is-block is-link is-fullwidth"
            class:is-danger={fehler}
            class:is-success={$state.connected}
            on:click={connect}>{fehler ? 'Verbindung fehlgeschlagen' : 'Verbinden'}</button><br>
</div>
