// src/pages/schueler.vue
<template>
  <q-page padding class="row">
    <div v-if="schueler" class="content">
      <div class="q-display-1">
        <span class="text-secondary cursor-pointer" color="secondary" v-on:click="$root.$emit('sucheSchueler', { klasse: true, id: schueler.Klasse })">{{schueler.Klasse}}</span> > {{schueler.Vorname}} {{schueler.Name}} ({{schueler.Geschlecht === 3 ? "&#x2642;" : "&#x2640;"}} {{alter}})
      </div>
      <q-card inline v-if="tabelle.length > 0" style="margin: 5px">
        <q-card-title>Leistungsübersicht</q-card-title>
        <q-card-separator />
        <q-card-main>
          <q-table
              :data="tabelle"
              :columns="columns"
              row-key="name"
              :pagination.sync="pagination"
              dense
              hide-bottom
              :style="{boxShadow: 'none'}"
            >
            <q-tr slot="body" slot-scope="props" :props="props">
              <q-td v-for="(col, i) in props.cols" :key="col.name" :props="props">
                <div :class="['4-', '5+', '5', '5-', '6'].some(n => n === col.value) ? 'bg-red' : ''" :style="{display: 'inline'}">{{col.value}}</div>
                <div v-if="props.row.data && props.row.data.noten[i] && props.row.data.noten[i].Lernentw" :style="{display: 'inline'}"><q-icon name="info" class="text-primary" />
                  <q-tooltip>{{props.row.data.noten[i].Lernentw}}</q-tooltip>
                </div>
                <q-tooltip v-if="col === props.cols[0]">
                  {{props.row.data.fach.Bezeichnung}}<br>{{props.row.data.fach.Bezeichnung != props.row.data.fach.Zeugnisbez ? props.row.data.fach.Zeugnisbez : ''}}
                </q-tooltip>
              </q-td>
            </q-tr>
          </q-table>
        </q-card-main>
      </q-card>
      <q-card inline style="width: 300px; margin: 5px">
        <q-card-title>{{schueler.AktSchuljahr}}/{{schueler.AktAbschnitt}}</q-card-title>
        <q-card-separator />
        <q-card-main>
          <img v-if="schuelerfoto" :src="schuelerfoto">
          <div v-else><i>Kein Foto vorhanden</i></div>
        </q-card-main>
        <q-card-main>
          <b>{{schueler.Vorname}} {{schueler.Name}}</b>
          <br>{{schueler.Strasse}}
          <br>{{schueler.PLZ}} {{schueler.OrtAbk}}
          <p></p>
          <br>{{schueler.Telefon}}
          <br>{{schueler.EMail}}
          <br>{{(new Date(schueler.Geburtsdatum).toLocaleDateString('de', {day: '2-digit', month: '2-digit', year: 'numeric'}))}}
        </q-card-main>
      </q-card>
      <q-card inline v-if="schueler.vermerke.length > 0" style="width: 300px; margin: 5px">
        <q-card-title>Vermerke</q-card-title>
        <q-card-separator />
        <q-card-main>
          <q-list v-for="(v, index) in schueler.vermerke" :key="index">
            <q-item>
              <q-item-main
                :label="v.Bemerkung"
                :sublabel="`${(new Date(v.Datum).toLocaleDateString('de', {day: '2-digit', month: '2-digit', year: 'numeric'}))} | ${v.GeaendertVon||v.AngelegtVon}`" />
            </q-item>
          </q-list>
        </q-card-main>
      </q-card>
      <q-card inline v-if="abschlussInfo.some(a => a)" style="width: 300px; margin: 5px">
        <q-card-title>Abschluss</q-card-title>
        <q-card-separator />
        <q-card-main v-for="abschluss in abschlussInfo" :key="abschluss">
          <div v-if="abschluss">{{abschluss}}</div>
        </q-card-main>
      </q-card>
    </div>
  </q-page>
</template>

<script>
export default {
  name: 'Schueler',
  data () {
    return {
      error: null,
      pagination: {
        descending: false,
        page: 1,
        rowsPerPage: 100
      }
    }
  },
  computed: {
    tabelle () { return Object.entries(this.faecher()).map(e => { return { name: e[0], ...e[1] } }) },
    columns () {
      if (this.tabelle.length === 0) return
      let a = [
        { name: 'Fach', field: 'name', label: 'Abschnitt', align: 'left' }
      ]
      this.tabelle.find(e => e).data.noten.forEach((hj, i) => {
        a.push({
          name: this.schueler.abschnitte[i].ID,
          field: row => row.data.noten[i] ? row.data.noten[i].NotenKrz : '',
          label: `${this.schueler.abschnitte[i].Jahr}/${this.schueler.abschnitte[i].Abschnitt}`,
          align: 'center'
        })
      })
      return a
    },
    schueler () { return this.$store.state.data.klasse[0] },
    schuelerfoto () { return `data:image/jpg;base64,${this.$store.state.data.schuelerfoto}` },
    alter () {
      const geburtstag = +new Date(this.schueler.Geburtsdatum)
      return ~~((Date.now() - geburtstag) / (31557600000))
    },
    abschlussInfo () {
      const abschluesse = [this.schueler.bk_abschluss, this.schueler.fhr_abschluss, this.schueler.abi_abschluss]
      const pruefungen = ['Berufsabschlussprüfung', 'FHR-Prüfung', 'Abiturprüfung']
      return abschluesse.map((abschluss, i) => {
        if (abschluss) {
          return `${this.schueler.schueler_in} ${(abschluss.Zulassung === '+' || abschluss.Zugelassen === '+') ? '' : 'nicht'} für die ${pruefungen[i]} zugelassen`
        }
      }).filter(e => e)
    }
  },
  methods: {
    faecher () {
      let faecher = {}
      this.schueler.abschnitte.forEach((abschnitt, i) => {
        abschnitt.noten.forEach(note => {
          if (faecher[note.fach.FachKrz]) {
            faecher[note.fach.FachKrz].data.noten[i] = note
          } else {
            faecher[note.fach.FachKrz] = { data: { noten: new Array(this.schueler.abschnitte.length), fach: note.fach } }
            faecher[note.fach.FachKrz].data.noten[i] = note
          }
        })
      })
      return faecher
    }
  }
}
</script>

// src/components/Schueler.svelte
<script>
  import { configData, state } from './../stores.js';
  import mysql from 'mysql'
  $: s = $state.schueler[0]
  async function foto (s) {
    const connection = mysql.createConnection($configData.db.connection)
    connection.connect()
    return new Promise((resolve, reject) => {
      connection.query('SELECT Foto FROM `schuelerfotos` WHERE `Schueler_ID` = ?', [s.ID],
        (err, rows) => {
          connection.end()
          if (err || rows.length===0) return reject(err);
          resolve(Buffer.from(rows[0].Foto, 'binary').toString('base64'));
      });
    });
  }
  // const faecher = new Set
  $: faecher = new Set(s.abschnitte.reverse().map(a => a.noten.map(n => n.fach.FachKrz)).flat())
</script>

<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image">
          {#await foto(s) then f}
            <img src="data:image/jpg;base64,{f}" alt="Foto" width="128" >
          {:catch}
            Kein Foto
          {/await}
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4">{s.Name}, {s.Vorname}</p>
        <p class="subtitle is-6">{s.Klasse}</p>
        {s.Strasse}, {s.PLZ} {s.OrtAbk}
        <p></p>
        <br>{s.Telefon || s.Fax || ''}
        <br>{s.EMail}
        <br>{(new Date(s.Geburtsdatum).toLocaleDateString('de', {day: '2-digit', month: '2-digit', year: 'numeric', timezone: 'Europe/Berlin'}))}
      </div>
    </div>
    <div class="content">
      <h5 class="title is-5"> Vermerke </h5>
      {#each s.vermerke.reverse() as v}
          – {v.Bemerkung} –
          {`${(new Date(v.Datum).toLocaleDateString('de', {day: '2-digit', month: '2-digit', year: 'numeric'}))} | ${v.GeaendertVon||v.AngelegtVon}`}
          <br>
      {:else} – keine –
      {/each}
    </div>
    <div class="content">
      <h5 class="title is-5"> Noten </h5>
      <table class="table is-narrow is-bordered is-striped">
        <thead>
          <td>Abschnitt</td>
          {#each Array.from(faecher) as f}
            <td class="has-text-centered">{f}</td>
          {/each}
        </thead>
        {#each s.abschnitte as hj}
        <tr>
        <td>{`${hj.Jahr}/${hj.Abschnitt}`}</td>
        {#each Array.from(faecher) as f}
          {#each [hj.noten.find(n => n.fach.FachKrz === f)||{}] as n}
            <td class="has-text-centered" style={parseInt(n.NotenKrz) > 4 ? 'background:tomato;':''}>
              <span class:kreis={n.Warnung==='+'}>{n.NotenKrz || '–'}</span>
            </td>
          {/each}
        {/each}
        </tr>
        {/each}
      </table>
    </div>
  </div>
</div>

<style>
  .kreis {
    border: 0.2rem solid red;
    border-radius: 20%;
    padding: 0.2rem;
  }
</style>
